server:
  port: 8081

spring:
  application:
    name: dictionaries
  datasource:
    url: jdbc:postgresql://localhost:5432/dictionaries
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver