server:
  port: 8083

spring:
  application:
    name: order-service
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/order
    username: postgres
    password: postgres

grpc:
  client:
    products-grpc-service:
      address: "static://localhost:9090"
      negotiationType: "PLAINTEXT"

logging:
  level:
    root: INFO
    ru.amironnikov: DEBUG