server:
  port: 8084

minio:
  endpoint: http://localhost:9000
  accessKey: amironnikov
  secretKey: LdKzOp9_G
  bucketName: images


spring:
  application:
    name: image-service
  cache:
    jcache:
      config: 'classpath:ehcache.xml'

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: ${SPRING_EUREKA_URL}

logging:
  level:
    root: INFO
    ru.amironnikov: DEBUG