server:
  port: 8084

minio:
  endpoint: http://localhost:9000
  accessKey: amironnikov
  secretKey: LdKzOp9_G
  bucketName: images


spring:
  cache:
    jcache:
      config: 'classpath:ehcache.xml'

logging:
  level:
    root: INFO
    ru.amironnikov: DEBUG