server:
  port: 8084

minio:
  endpoint: ${MINIO_URL}
  accessKey: ${MINIO_USERNAME}
  secretKey: ${MINIO_PASSWORD}
  bucketName: images


spring:
  application:
    name: image-service
  cache:
    jcache:
      config: 'classpath:ehcache.xml'

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: ${SPRING_EUREKA_URL}

logging:
  level:
    root: INFO
    ru.amironnikov: DEBUG