grpc:
  server:
    port: 9091
    security:
      enabled: false

spring:
  application:
    name: dictionaries-service
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: ${SPRING_EUREKA_URL}

logging:
  level:
    root: INFO
    ru.amironnikov: DEBUG